#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

################################################################################
## Script written by Rafael Fernández López <ereslibre@kde.org>               ##
##                                                                            ##
##                                                                            ##
## This script is of PUBLIC DOMAIN.                                           ##
################################################################################

#### CONFIGURE #################################################################

INSTALL_PREFIX = "/usr/local"
INSTALL_COMMAND = "sudo make install/fast"
MAKE_OPTIONS = "-j5"
BUILD_TYPE = "Debug"
SOURCE_DIR = File.expand_path "~/proyectos"
CONFIG_FILE = File.expand_path "~/.kdebuild"
DEFAULT_OBJECTIVE = :full_kde

#### INTERNAL ##################################################################

def user_has_config
    File.exists? File.expand_path("~/.kdebuild")
end

def user_config
  File.new(File.expand_path("~/.kdebuild")).read
end

def user_has_own_config
  File.exists? File.expand_path("~/.kdebuild-own")
end

def user_own_config
  File.new(File.expand_path("~/.kdebuild-own")).read
end

def known_task(task)
  $tasks.has_key? task.to_sym
end

begin
  require "json" if (user_has_config or user_has_own_config)
rescue LoadError
  puts "!!! You have set your own configuration on #{File.expand_path("~/.kdebuild-own")}, and this"
  puts "    format is JSON. In order to be able to understand the configuration file you need to run:"
  puts
  puts "    # sudo gem install json"
  Process.exit 1
end

$stderr.reopen "/dev/null"

ENV["PATH"] = "#{INSTALL_PREFIX}/bin:#{ENV["PATH"]}"
ENV["PKG_CONFIG_PATH"] = "#{INSTALL_PREFIX}/lib/pkgconfig:#{ENV["PKG_CONFIG_PATH"]}"

require "uri"
require "net/http"
require "fileutils"

$options = {}
$options[:build_only] = false
$options[:omit_dependencies] = false
$options[:list_available_tasks] = false
$options[:force_cmake] = false
$options[:verbose] = false

$tasks = Hash.new
$failed_tasks = { :configure => Array.new,
                  :build     => Array.new,
                  :install   => Array.new }
$succeeded_tasks = Array.new
$skipped_tasks = Array.new

def info(info_msg)
  puts "\t-> #{info_msg}..."
end

def warn(warn_msg)
  puts "\t!!! #{warn_msg}"
end

def retrieve_file(remote, local)
  uri = URI.parse remote
  Net::HTTP.start(uri.host) do |http|
    resp = http.get(uri.path)
    open(File.expand_path(local), "wb") do |file|
      file.write(resp.body)
    end
  end
end

retrieve_file("http://media.ereslibre.es/kdebuild/kdebuild", "~/.kdebuild") if not user_has_config

class Repository

  attr_reader :uri

  SVN_REPO = 0
  GIT_REPO = 1

  def initialize(uri, type)
    @uri = uri
    @type = type
  end

  def clone
    if @type == SVN_REPO
      info "Doing checkout of SVN repository"
      IO.popen("svn co #{uri} . &> /dev/null") {}
    else
      info "Cloning git repository"
      IO.popen("git clone #{uri} . &> /dev/null") {}
    end
    true
  end

  def update
    if @type == SVN_REPO
      info "Updating SVN repository"
      (IO.popen("svn up").read =~ /Updated to revision \d+\./) != nil
    else
      info "Updating git repository"
      IO.popen("git pull origin master").read !~ /Already up-to-date\./
    end
  end

end

class Task

  attr_reader :name, :repository, :dependencies

  CMAKE = 0
  QMAKE = 1

  def initialize(name, source, repository, dependencies = nil, build_system = CMAKE)
    @name = name
    @source = source
    @repository = repository
    @dependencies = dependencies
    @build_system = build_system
    @install_command = INSTALL_COMMAND
    @touched = false
    @no_news = true
    $tasks[name] = self
  end

  def update
    return if @touched
    source_dir = File.join SOURCE_DIR, @source
    if not File.exists? source_dir
      FileUtils.mkdir_p source_dir
      Dir.chdir source_dir do
        @no_news = not(@repository.clone)
      end
    else
      Dir.chdir source_dir do
        @no_news = not(@repository.update)
      end
    end
  end

  def build(omit_banner = false)
    return if @touched
    for dependency in @dependencies
      run_task dependency
    end if @dependencies and not $options[:omit_dependencies]
    return if not @repository # Meta-task
    if not $options[:build_only] and not $options[:force_cmake] and @no_news
      puts "\t\tSkipping build and install phases. Repository was up-to-date"
      puts
      $skipped_tasks << self
      @touched = true
      return
    end
    puts "=== Running task: #{@name} ===" if not omit_banner
    if @build_system == CMAKE
      build_dir = File.join SOURCE_DIR, @source, "build"
      if $options[:force_cmake]
        FileUtils.rm_rf build_dir if File.exists? build_dir
      end
      need_cmake = false
      if not File.exists? build_dir
        Dir.mkdir build_dir
        need_cmake = true
      end
    else
      build_dir = File.join SOURCE_DIR, @source
      need_cmake = true
      @install_command = "sudo make install"
    end
    Dir.chdir build_dir do
      res = nil
      if need_cmake
        info "Running #{@build_system == CMAKE ? "cmake" : "qmake"}"
        own_configs = ""
        if user_has_own_config
          begin
            config = JSON.parse user_own_config
            if config.has_key? @name.to_s and config[@name.to_s].has_key? "configure"
              own_configs = config[@name.to_s]["configure"]
              puts "\t\tUsing own configuration settings: #{own_configs}"
            else
              puts "\t\tNo own configuration settings found. Using defaults"
            end
          rescue JSON::ParserError
            puts "!!! Your own settings file under #{File.expand_path("~/.kdebuild-own")} seems to be an invalid JSON file"
            puts
            puts "    Need help ? Try: http://www.jsonlint.com/"
            Process.exit 1
          end
        end
        if @build_system == CMAKE
          if $options[:verbose]
            system "cmake -DCMAKE_BUILD_TYPE=#{BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=#{INSTALL_PREFIX} #{own_configs} .."
          else
            IO.popen("cmake -DCMAKE_BUILD_TYPE=#{BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=#{INSTALL_PREFIX} #{own_configs} .. &> /dev/null") {}
          end
        else
          if $options[:verbose]
            system "qmake"
          else
            IO.popen("qmake &> /dev/null") {}
          end
        end
      end
      info "Compiling"
      res = nil
      if $options[:verbose]
        res = system "make #{MAKE_OPTIONS}"
      else
        IO.popen("make #{MAKE_OPTIONS} &> /dev/null") {}
        res = ($?.to_i == 0)
      end
      if not res
        $failed_tasks[:build] << self
        warn "Build failed"
      else
        info "Installing"
        res = nil
        if $options[:verbose]
          res = system @install_command
        else
          IO.popen("#{@install_command} &> /dev/null") {}
          res = ($?.to_i == 0)
        end
        if not res
          $failed_tasks[:install] << self
          warn "Installation failed"
        else
          $succeeded_tasks << self
        end
      end
      puts
      @touched = true
    end
  end

  def update_and_build
    return if @touched
    for dependency in @dependencies
      $tasks[dependency].update_and_build if $tasks[dependency]
    end if @dependencies and not $options[:omit_dependencies]
    return if not @repository # Meta-task
    puts "=== Running task: #{@name} ==="
    update; build true
  end

end

def print_tasks
  $tasks.each_value do |task|
    if not task.dependencies or task.dependencies.empty?
      puts "\t-> #{task.name} (No dependencies)"
    else
      puts "\t-> #{task.name} (Depends on: #{task.dependencies.join ", "})"
    end
    if task.repository
      puts "\t\t#{task.repository.uri}"
    else
      puts "\t\tMeta task (no repository associated)"
    end
  end
end

def run_task(task)
  the_task = $tasks[task]
  if the_task
    if $options[:build_only]
      the_task.build
    else
      the_task.update_and_build
    end
  else
    puts "!!! Unknown task: #{task}. Existing tasks:"
    print_tasks
  end
end

def parse_tasks(config_tasks)
  begin
    config = JSON.parse config_tasks
    config.each do |task, settings|
      next if known_task task
      source = nil
      repository = nil
      build_system = nil
      if settings.has_key? "source"
        source = settings["source"]
      else
        source = task
      end
      if settings.has_key?("repository") and settings.has_key?("repositoryType")
        task_repository = settings["repository"]
        task_repositoryType = (settings["repositoryType"].downcase == "svn" ? Repository::SVN_REPO : Repository::GIT_REPO)
        repository = Repository.new task_repository, task_repositoryType
      end
      if settings.has_key? "buildSystem"
        if settings["buildSystem"].downcase == "cmake"
          build_system = Task::CMAKE
        elsif settings["buildSystem"].downcase == "qmake"
          build_system = Task::QMAKE
        else
          puts "!!! Unknown buildSystem (#{settings["buildSystem"]}) for task #{task}"
          Process.exit 1
        end
      elsif repository
        build_system = Task::CMAKE
      end
      if settings.has_key? "dependencies"
        if settings["dependencies"].include? task
          puts "!!! Task #{task} includes itself as a dependency. Pretty weird, and the result will probably be 42"
          Process.exit 1
        end
        Task.new task.to_sym, source, repository, settings["dependencies"].map { |e|
          d = e.to_sym
          if not known_task d
            puts "!!! Task #{task} depends on unknown task #{e}"
            Process.exit 1
          end
          d
        }, build_system
      else
        Task.new task.to_sym, source, repository, nil, build_system
      end
    end
  rescue JSON::ParserError
    puts "!!! Your own settings file under #{File.expand_path("~/.kdebuild-own")} seems to be an invalid JSON file"
    puts
    puts "    Need help ? Try: http://www.jsonlint.com/"
    Process.exit 1
  end
end

#### PARSE DEFINED TASKS #######################################################

if user_has_config
    parse_tasks user_config
end

#### PARSE USER DEFINED TASKS ##################################################

if user_has_own_config
    parse_tasks user_own_config
end

#### PARSE ARGUMENTS AND START WORKING #########################################

require "optparse"

OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename $0} [-bofv] [-l] [task1, task2, ...]"
  opts.on("-b", "--build-only", "Do not update. Only build") do
    $options[:build_only] = true
  end
  opts.on("-o", "--omit-dependencies", "Omit dependencies. Execute only the provided tasks") do
    $options[:omit_dependencies] = true
  end
  opts.on("-f", "--force-cmake", "Force CMake (or qmake) execution. Cleans old build(s)") do
    $options[:force_cmake] = true
  end
  opts.on("-v", "--verbose", "Output verbosity") do
    $options[:verbose] = true
  end
  opts.on("-l", "--list-available-tasks", "List available tasks") do
    $options[:list_available_tasks] = true
  end
end.parse!

if $options[:list_available_tasks]
  puts "Available tasks:"
  print_tasks
  Process.exit
end

if ARGV.empty?
  run_task DEFAULT_OBJECTIVE
else
  for arg in ARGV
    run_task arg.to_sym
  end
end

if not $skipped_tasks.empty?
  puts "*** Skipped tasks:"
  $skipped_tasks.each do |task|
    puts "\t- #{task.name}"
  end
  puts
end

if not $succeeded_tasks.empty?
  puts "*** Succeeded tasks:"
  $succeeded_tasks.each do |task|
    puts "\t- #{task.name}"
  end
  puts
end

$failed_tasks.each do |phase, tasks|
  next if tasks.empty?
  puts "!!! Failed tasks at #{phase} phase"
  tasks.each do |task|
    puts "\t- #{task.name}"
  end
  puts
end
